DROP DATABASE IF EXISTS jerky2_db;

CREATE DATABASE jerky2_db;

USE jerky2_db;
 
CREATE TABLE jerky (
  id INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR (12) NULL,
  flavor VARCHAR(45) NULL,
  price DECIMAL(10,2) NULL,
  purchased BOOLEAN DEFAULT false,
  PRIMARY KEY (id)
);
CREATE TABLE user (
id INT NOT NULL AUTO_INCREMENT,
`username` VARCHAR (12) NULL,
`email` VARCHAR (30) NULL,
`password` VARCHAR (12) NULL,
PRIMARY KEY (id)
);